version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: jdbc:postgresql://dpg-cpmd5cdds78s73ag97h0-a:5432/asn2_db_ic45
      POSTGRES_USER: asn2_db_ic45_user
      POSTGRES_PASSWORD: ab1jpsJmYxqaBALthCE1C45eAnCumzzN
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://asn2_db_ic45_user:ab1jpsJmYxqaBALthCE1C45eAnCumzzN@dpg-cpmd5cdds78s73ag97h0-a.oregon-postgres.render.com/asn2_db_ic45
      SPRING_DATASOURCE_USERNAME: asn2_db_ic45_user
      SPRING_DATASOURCE_PASSWORD: ab1jpsJmYxqaBALthCE1C45eAnCumzzN
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SRPING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres

volumes:
  postgres_data:
